config/routes.rb
Spree::Core::Engine.routes.draw do
  # solidus_auth_devise-master/config/routes.rb
  unless Spree::Auth::Config.draw_frontend_routes

    devise_for(:spree_user, {
        class_name: 'Spree::User',
        controllers: {
            sessions: 'spree/user_sessions',
            registrations: 'spree/user_registrations',
            passwords: 'spree/user_passwords',
            confirmations: 'spree/user_confirmations'
        },
        skip: [:unlocks, :omniauth_callbacks],
        path_names: { sign_in: 'login', sign_out: 'logout' },
        path: '/users'
    })

    resources :users, only: [:edit, :update]

    devise_scope :spree_user do
      get '/login', to: 'user_sessions#new', as: :login
      post '/login', to: 'user_sessions#create', as: :create_new_session
      match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
      get '/signup', to: 'user_registrations#new', as: :signup
      post '/signup', to: 'user_registrations#create', as: :registration
      get '/password/recover', to: 'user_passwords#new', as: :recover_password
      post '/password/recover', to: 'user_passwords#create', as: :reset_password
      get '/password/change', to: 'user_passwords#edit', as: :edit_password
      put '/password/change', to: 'user_passwords#update', as: :update_password
      get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
    end

    get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
    put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration

    resources :account, controller: 'users'

    match '/access' => 'users#access', as: 'user_access', via: [:get]
    match '/access_login' => 'users#access_login', as: 'user_access_login', via: [:put, :post]
  end

  ##
  # Admins
  match '/admin/products/:id/erase', to: 'admin/products#erase', as: 'admin_erase_product', via: [:delete]

  ##
  # Seller
  resources :store_payment_methods
  get '/accepted_payments', to: 'store_payment_methods#index', as: 'accepted_payments'

  ##
  # Buyer

  resources :variants

  # Trading
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'order_cancel'


  get '/cart_link_dropdown', to: 'orders#cart_link_dropdown', as: 'cart_link_dropdown'

end

Rails.application.routes.draw do
  default_url_options :host => (Rails.env.production? ? 'shoppn.com' : 'localhost')

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  #########################
  # Filtering bots
  get '/:a/:b.php', to: 'errors#not_found'
  get '/:a.php', to: 'errors#not_found'

  ####################################################
  # Admins

  resources :site_categories, path: 'admin/site_categories'

  ####################################################
  # Additions to Spree
  namespace :spree, path: '/' do
    resources :stores, only: [:show, :index]
  end

  ##
  # Users
  namespace :users do
    resources :resource_action, only: [:index, :create, :destroy]
  end

  # Buyers

  get '/sellers/:id', to: 'sellers#show', as: :seller

  # Payments
  match '/payment_notifications/log' => 'payment_notifications#log', via: [:get, :put, :post], as: 'log_payment_notification'
  resources :payment_notifications

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/retail/product.rb
require 'csv'
require 'open-uri'

class Retail::Product < ::RetailScraperRecord

  self.table_name = 'retail_products'

  attr_accessor :temp_specs, :categories_object

  validates_presence_of :retail_site_id, :title

  ################################
  # Scopes

  belongs_to :retail_site, class_name: 'Retail::Site', foreign_key: :retail_site_id
  belongs_to :retail_store, class_name: 'Retail::Store', foreign_key: :retail_store_id, optional: true

  has_many :product_specs, class_name: 'Retail::ProductSpec', foreign_key: :retail_product_id, dependent: :delete_all
  alias_method :specs, :product_specs
  has_many :product_photos, class_name: 'Retail::ProductPhoto', foreign_key: :retail_product_id, dependent: :destroy
  alias_method :photos, :product_photos

  has_many :migrations, class_name: 'Retail::ProductToSpreeProduct', foreign_key: :retail_product_id
  has_many :spree_products, class_name: 'Spree::Product', through: :migrations, foreign_key: :spree_product_id

  ##################################
  # Callbacks

  before_save :convert_attributes


  def store_id
    retail_store.try(:retail_site_store_ids)
  end

  def category_names
    (JSON.load(categories) || []).collect { |h| h['name'] }
  rescue JSON::ParserError
    []
  end

  def other_site_categories
    ::Retail::OtherSiteCategory.find_for_retail_product(self)
  end

  def leaf_other_site_category
    other_site_categories.last
  end

  ##
  # Deepest level of category, dependent on categories property specifying the category path.
  # @return <SiteCategory>
  def leaf_site_category
    categories.present? ? ::SiteCategory.find_by_full_path(retail_site.name, category_names) : []
  end
  alias_method :site_category, :leaf_site_category

  # Mixed spec name and values together, w/ spec.name as its own attribute name, e.g., "max_size": 10
  def specs_list
    # product_specs.collect{|spec| [spec.name, spec.value_1, spec.value_2].compact }.flatten.uniq Mixed spec name and values together
    product_specs.collect { |spec| { spec.name_as_key => spec.value_1} }
  end

  def as_json(options = {})
    h = super(options)
    # h['specs'] = product_specs.collect(&:as_json)
    # h['product_photos'] = product_photos.collect(&:as_json)
    h
  end

  ##
  # Grouped up list of values by common spec name.
  # @return <Hash of String => Set of values>
  def spec_name_to_values_group(which_product_specs = nil)
    h = {}
    (which_product_specs || self.product_specs).each do|spec|
      set = h[spec.name] || Set.new
      set << spec.object_value
      h[spec.name] = set
    end
    h
  end

  ###############################
  # Util methods

  ##
  # Delete duplicate specs.
  def clean_product_specs!
    existing_specs = Set.new
    product_specs.each do |spec|
      if existing_specs.include?(spec.value_for_comparison)
        puts "  - #{spec}"
        spec.destroy
      else
        existing_specs << spec
      end
    end
  end

  ##
  # Matched or created ProductSpec would be yielded in block.
  # @specs <Array of Retail::ProductSpec or a Hash w/ spec name to value >
  # @return <Array of Retail::ProductSpec> updated list
  #
  def find_or_create_product_specs!(specs, &block)
    matching_specs = []
    group = self.product_specs.group_by(&:name)
    logger.info "  \\ given specs #{specs}"
    (specs || [] ).each do|obj|
      _name = nil
      _value = nil
      if obj.is_a?(::Retail::ProductSpec)
        _name = obj.name
        _value = obj.object_value
      elsif obj.is_a?(Hash)
        # model hash format like [{"name"=>"available sizes", "value_1"=>"S M"}, {"name"=>"available colors", "value_1"=>""}]
        obj_stringified = obj.stringify_keys
        sorted_keys = obj_stringified.keys.sort
        if sorted_keys == %w{name value_1}
          _name = obj_stringified['name']
          _value = obj_stringified['value_1']
        else # dynamic keys to values: 'material' => 'wool', 'color' => 'black'
          _name = obj_stringified.keys.first
          _value = obj_stringified[_name]
        end
      end
      next if _name.blank?
      # is new
      cur_set = group[_name] || []
      if (cur_spec = cur_set.find{|_spec| [_spec.value_1, _spec.value_2] == [_value, nil] } )
        matching_specs << cur_spec
      else
        cur_spec = Retail::ProductSpec.create(retail_product_id: id, name: _name, value_1: _value)
        matching_specs << cur_spec
      end
      yield cur_spec if block_given?
    end
    matching_specs
  end

  def fix_product_categories!
    self.update_attributes(categories: retail_site.scraper.find_categories_object(page.make_mechanize_page).to_json)
  end

  ##
  # @return <Spree::Product>
  def create_as_spree_product(force_recreate = false, other_attributes = {}, &block)
    product = force_recreate ? nil : ::Retail::ProductToSpreeProduct.where(retail_product_id: id).first.try(:spree_product)
    unless product
      product = self.class.make_spree_product(self)
      product.attributes = other_attributes if other_attributes.size > 0
      product.save
      ::Retail::ProductToSpreeProduct.create(retail_product_id: id, spree_product_id: product.id)
      product.copy_images_from_retail_product!(self)
      product.create_categories_taxon!(self)
      product.copy_product_specs_from_retail_product!(self)
    end
    yield product if block_given?
    product
  end

  ##
  # @retail_product <Retail::Product> new but not saved
  def self.make_spree_product(retail_product)
    product = ::Spree::Product.new(
        name: retail_product.title.strip,
        description: retail_product.description,
        available_on: Time.now,
        shipping_category_id: ::Spree::ShippingCategory.default.try(:id),
        price: retail_product.price
      )
    product
  end

  protected

  def convert_attributes
    if categories_object.is_a?(Hash)
      self.categories = categories_object.to_json
    end
  end

end

app/controllers/spree/products_controller.rb
# frozen_string_literal: true

module Spree
  class ProductsController < Spree::StoreController
    before_action :load_product, only: :show
    before_action :load_taxon, only: :index

    helper 'spree/taxons', 'spree/taxon_filters'

    respond_to :html

    def index
      @searcher = Spree::Core::Search::Base.new(params.merge(include_images: true) ).tap do |searcher|
        searcher.current_user = try_spree_current_user
        searcher.pricing_options = current_pricing_options
      end

      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    def show
      @variants = @product.
          variants_including_master.
          display_includes.
          with_prices(current_pricing_options).
          includes([:option_values, :images])

      @product_properties = @product.product_properties.includes(:property)
      @taxon = Spree::Taxon.find(params[:taxon_id]) if params[:taxon_id]
    end

    private

    def accurate_title
      if @product
        @product.meta_title.blank? ? @product.name : @product.meta_title
      else
        super
      end
    end

    def load_product
      if try_spree_current_user.try(:has_spree_role?, "admin")
        @products = Spree::Product.with_deleted
      else
        @products = Spree::Product.available
      end
      @product = @products.friendly.find(params[:id])
    end

    def load_taxon
      @taxon = Spree::Taxon.find(params[:taxon]) if params[:taxon].present?
    end
  end
end

app/views/spree/admin/products/_form.html.erb
<%= f.hidden_field(:master_product_id) -%>
<div data-hook="admin_product_form_fields">

  <div class="row">

    <div class="left col-9" data-hook="admin_product_form_left">
      <div data-hook="admin_product_form_name">
        <%= f.field_container :name do %>
          <%= f.label :name, class: 'required' %>
          <%= f.text_field :name, class: 'fullwidth title', required: true %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_description">
        <%= f.field_container :description do %>
          <%= f.label :description %>
          <%= f.text_area :description, {rows: "#{unless @product.has_variants? then '22' else '15' end}", class: 'fullwidth'} %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>
    </div>

    <div class="right col-3" data-hook="admin_product_form_right">
      <div data-hook="admin_product_form_price">
        <%= f.field_container :price do %>
          <%= f.label :price, class: Spree::Config.require_master_price ? 'required' : '' %>
          <%= render "spree/admin/shared/number_with_currency", f: f,
                     amount_attr: :price,
                     required: Spree::Config.require_master_price,
                     currency: Spree::Config.default_pricing_options.currency %>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <% if show_rebuild_vat_checkbox? %>
        <%= render "spree/admin/shared/rebuild_vat_prices_checkbox", form: f, model_name: "product" %>
        <div class="clearfix"></div>
      <% end %>

      <div class="row">

        <div data-hook="admin_product_form_cost_price" class="col-12">
          <%= f.field_container :cost_price do %>
            <%= f.label :cost_price %>

            <%= render "spree/admin/shared/number_with_currency", f: f, amount_attr: :cost_price, currency_attr: :cost_currency %>

            <%= f.error_message_on :cost_price %>
            <%= f.error_message_on :cost_currency %>
          <% end %>
        </div>
      </div>

      <div class="clear"></div>

      <div data-hook="admin_product_form_available_on">
        <%= f.field_container :available_on do %>
          <%= f.label :available_on %>
          <%= f.field_hint :available_on %>

          <%= render "spree/admin/shared/datepicker", f: f, date_attr: :available_on %>

          <%= f.error_message_on :available_on %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_promotionable">
        <%= f.field_container :promotionable do %>
          <label>
            <%= f.check_box :promotionable %>
            <%= Spree::Product.human_attribute_name(:promotionable) %>
          </label>
          <%= f.field_hint :promotionable %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_sku">
        <%= f.field_container :sku do %>
          <%= f.label :sku, t('spree.master_sku') %>
          <%= f.text_field :sku, size: 16 %>
        <% end %>
      </div>

      <% if @product.has_variants? %>
        <div data-hook="admin_product_form_multiple_variants">
          <%= f.label :skus, t('spree.skus') %>
          <span class="info">
            <%= t('spree.info_product_has_multiple_skus', count: @product.variants.count) %>
            <ul class="text_list">
              <% @product.variants.first(5).each do |variant| %>
                <li><%= link_to variant.sku, spree.edit_admin_product_variant_path(@product, variant) %></li>
              <% end %>
            </ul>
            <% if @product.variants.count > 5 %>
              <%= t('spree.info_number_of_skus_not_shown', count: @product.variants.count - 5) %>
            <% end %>
          </span>
          <div class="info-actions">
            <% if can?(:admin, Spree::Variant) %>
              <%= link_to_with_icon 'th-large', t('spree.manage_variants'), admin_product_variants_url(@product) %>
            <% end %>
          </div>
        </div>
      <% else %>
        <div id="shipping_specs" class="row">
          <% [:height, :width, :depth, :weight].each_with_index do |field, index| %>
            <div id="shipping_specs_<%= field %>_field" class="col-6">
              <div class="field">
                <%= f.label field %>
                <%= f.text_field field, value: number_with_precision(@product.send(field), precision: 2) %>
              </div>
            </div>
          <% end %>
        </div>

      <% end %>

      <%= f.hidden_field(:shipping_category_id, value: ::Spree::ShippingCategory.default.try(:id) || 1 ) -%>
      <%= f.hidden_field(:tax_category_id, value: ::Spree::TaxCategory.default.try(:id) || 1 ) -%>
    </div>

  </div>

  <div class="row">

    <div class="col-9">
      <div data-hook="admin_product_form_taxons">
        <%= f.field_container :taxons do %>
          <%= f.label :taxon_ids, plural_resource_name(Spree::Taxon) %><br />
          <%= f.hidden_field :taxon_ids, value: @product.taxon_ids.join(',') %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_option_types">
        <%= f.field_container :option_types do %>
          <%= f.label :option_type_ids, plural_resource_name(Spree::OptionType) %>
          <%= f.hidden_field :option_type_ids, value: @product.option_type_ids.join(',') %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_meta">
        <div data-hook="admin_product_form_meta_title">
          <%= f.field_container :meta_title do %>
            <%= f.label :meta_title %>
            <%= f.text_field :meta_title, class: 'fullwidth' %>
          <% end %>
        </div>

        <div data-hook="admin_product_form_meta_keywords">
          <%= f.field_container :meta_keywords do %>
            <%= f.label :meta_keywords %>
            <%= f.text_field :meta_keywords, class: 'fullwidth' %>
          <% end %>
        </div>

        <div data-hook="admin_product_form_meta_description">
          <%= f.field_container :meta_description do %>
            <%= f.label :meta_description %>
            <%= f.text_field :meta_description, class: 'fullwidth' %>
          <% end %>
        </div>
      </div>
    </div>

  </div>

  <div class="clear"></div>

  <div data-hook="admin_product_form_additional_fields"></div>

  <div class="clear"></div>
</div>

app/views/spree/admin/products/_product_upload_image.html.haml
:ruby
  # Required locals:
  #   f: <FormBuilder>
  # Optional locals:
  #   index: <Integer> can be used as suffix to form input's ID
  #   row_id: <String>
  index = nil unless defined?(index)
  id_suffix = index ? "_#{index}" : ''
  row_id = 'new_product_image_row' unless defined?(row_id)
  style = 'display: none;' if row_id == 'new_product_image_row'
%tr(id="#{row_id}" class="product-image-row" style="#{style}")
  %td
    - if can?(:update_positions, Spree::Image)
      %span.handle
  %td
  %td
    - if @variants
      = f.select :image_viewable_ids, options_for_select(@variants), {}, name: "product[uploaded_images][][viewable_id]", id:"product_image_viewable_id#{id_suffix}", class:'form-control fullwidth', autocomplete:'off'
  %td
    = f.text_field('image_alts', name: "product[uploaded_images][][alt]", id:"product_image_alt#{id_suffix}")
  %td.actions
    - if can?(:create, Spree::Image)
      = f.file_field('uploaded_images', name: "product[uploaded_images][][attachment]", id:"product_uploaded_image#{id_suffix}")

app/views/spree/admin/products/_product_variant_row.html.haml
:ruby
  # Required locals:
  #   product
  #   variant
%tr(id="#{spree_dom_id variant}" data-hook="variants_row" class="#{ 'deleted' if variant.deleted? }")
  %td
    - if can? :update_positions, Spree::Variant
      %span.handle
  %td
    %table
      %tbody
        = fields_for variant do|vf|
          - @product.option_types.each do |option_type|
            %tr
              %td
                = vf.label 'option_value_ids', option_type.presentation
              %td
                = vf.collection_select 'option_value_ids', option_type.option_values,
                  :id, :presentation, { include_blank: true }, |
                  { name: 'variant[option_value_ids][]',  class: 'custom-select', |
                    id: "option_value_ids_#{option_type.presentation}" } |
    -#{variant.options_text }
  %td
    = fields_for variant do|vf|
      = vf.label(:price)
      = render 'spree/admin/shared/number_with_currency', f: vf, amount_attr: :price, currency: variant.default_price.currency
      %br/
      = vf.label :sku
      = vf.text_field(:sku)
  %td.actions
    - if can?(:update, variant)
      = link_to_with_icon 'check', t('spree.actions.save'), api_product_variant_path(product, variant), no_text: true, data: {action: 'save'}
      = link_to_with_icon 'cancel', t('spree.actions.cancel'), nil, no_text: true, data: {action: 'cancel'}
      = link_to_edit(variant, url: polymorphic_url([:edit, :admin, product, variant], host:'localhost' ), no_text: true) unless variant.deleted?
    - if can?(:destroy, variant)
      &nbsp;
      = link_to_delete(variant, url: polymorphic_url([:admin, product, variant], host:'localhost' ), no_text: true) unless variant.deleted?
  - if @product.variants.empty?
    %tr
      %td(colspan="4") #{ t('spree.none') }

app/views/spree/admin/products/edit.html.haml
- content_for :page_actions do
  - if can?(:create, Spree::Product)
    %li#new_product_link
      = link_to t('spree.new_product'), new_object_url, id: 'admin_new_product', class: 'btn btn-primary'
  - if defined?(Spree::Frontend::Engine)
    %li#view_product_link
      = link_to t('spree.view_product'), spree.product_path(@product), id: 'admin_view_product', class: 'btn btn-primary ml-2'

= render partial: 'spree/admin/shared/product_tabs', locals: { current: 'Product Details' }
= render partial: 'spree/shared/error_messages', locals: { target: @product }

- admin_breadcrumb(t('spree.product_details'))

= form_for [:admin, @product], html: { multipart: true } do |f|
  %fieldset(class="no-border-top")
    = render partial: 'form_in_one', locals: { f: f }
  - if can?(:update, @product)
    = render partial: 'spree/admin/shared/edit_resource_links'
%br/
%br/

app/views/spree/admin/products/erase.js.erb
$("#spree_product_<%= @product.id -%>").fadeOut();

app/views/spree/admin/products/index.html.erb
<% show_seller = spree_current_user.admin? && params[:user_id].nil?
-%>
<% admin_layout 'full-width' %>

<% admin_breadcrumb(plural_resource_name(Spree::Product)) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.new_product'), new_object_url, class: 'btn btn-primary' %>
  </li>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter_title do %>
  <%= t('spree.search') %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {f: f} %>
      <div class="row" data-hook="admin_products_index_search" >
        <div class="col-6">
          <div class="field">
            <%= f.label :name_cont, Spree::Product.human_attribute_name(:name) %>
            <%= f.text_field :name_cont, size: 15 %>
          </div>
        </div>

        <div class="col-4">
          <div class="field">
            <%= f.label :with_variant_sku_cont, Spree::Variant.human_attribute_name(:sku) %>
            <%= f.text_field :with_variant_sku_cont, size: 15 %>
          </div>
        </div>

        <div class="col-2">
          <div class="field checkbox">
            <label>
              <%= f.check_box :with_deleted, { checked: params[:q][:with_deleted] == 'true' }, 'true', 'false' %>
              <%= t('spree.show_deleted') %>
            </label>
          </div>
        </div>
      </div>

      <div class="actions filter-actions" data-hook="admin_products_index_search_buttons">
        <%= button_tag t('spree.search'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<% end %>

<div id="new_product_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_products">
    <colgroup>
      <col style="width: 15%;">
      <col style="width: 5%;">
      <col style="width: <%= show_seller ? 40 : 50 -%>%;">
      <col style="width: <%= show_seller ? 10 : 15 -%>%;">
      <% if show_seller -%><col style="width: 15%"><% end -%>
      <col style="width: 15%;">
    </colgroup>
    <thead>
    <tr data-hook="admin_products_index_headers">
      <th><%= Spree::Variant.human_attribute_name(:sku) %></th>
      <th></th>
      <th><%= sort_link @search,:name, Spree::Product.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
      <th class="align-right"><%= sort_link @search,:master_default_price_amount, Spree::Product.human_attribute_name(:price), {}, {title: 'admin_products_listing_price_title'} %></th>
      <% if show_seller -%><th class="align-center">Seller</th><% end -%>
      <th data-hook="admin_products_index_header_actions" class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @collection.each do |product| %>
      <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows">
        <td><%= product.sku %></td>
        <td class="align-center">
          <%= render 'spree/admin/shared/image', image: product.gallery.images.first, size: :mini %>
        </td>
        <td><%= link_to product.try(:name), edit_admin_product_path(product) %>
          <br/><span class="text-muted"><%= product.variants.count -%> variants</span>
        </td>
        <td class="align-right"><%= product.display_price.to_html %></td>
        <% if show_seller -%>
        <td class="align-center"><%= link_to(product.user.username, admin_products_path(user_id: product.user_id), title: product.user_id ) if product.user -%></td>
        <% end -%>
        <td class="actions" data-hook="admin_products_index_row_actions">
          <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
          &nbsp;
          <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
          &nbsp;
          <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>

          <%= link_to '', admin_erase_product_path(product), method: :delete, remote: true, class:'fa fa-eraser icon_link no-text', 'data-confirm' => 'Sure to permanently erase all related records and images?' if can?(:erase, product) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
               resource: Spree::Product,
               new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>

app/views/spree/admin/products/new.html.haml
- admin_breadcrumb link_to(plural_resource_name(Spree::Product), spree.admin_products_path)
- admin_breadcrumb @master_product ? t('spree.your_listing_of_this_product') : t('spree.new_product')

= render partial: 'spree/shared/error_messages', locals: { target: @product }

= form_for [:admin, @product], method: :post, url: admin_products_path, html: { multipart: true } do |f|
  %fieldset(data-hook="new_product")


    -# if @master_product || Rails.env.development? || params[:form] == 'form_in_one'
    = render partial: 'form_in_one', locals: { f: f }
    -# else
    -#  %legend(align="center") #{t('spree.new_product') }
    -#  = render partial: 'form', locals: { f: f }

    = render partial: 'spree/admin/shared/new_resource_links'