config/routes.rb
Spree::Core::Engine.routes.draw do
  # solidus_auth_devise-master/config/routes.rb
  unless Spree::Auth::Config.draw_frontend_routes

    devise_for(:spree_user, {
        class_name: 'Spree::User',
        controllers: {
            sessions: 'spree/user_sessions',
            registrations: 'spree/user_registrations',
            passwords: 'spree/user_passwords',
            confirmations: 'spree/user_confirmations'
        },
        skip: [:unlocks, :omniauth_callbacks],
        path_names: { sign_in: 'login', sign_out: 'logout' },
        path: '/users'
    })

    resources :users, only: [:edit, :update]

    devise_scope :spree_user do
      get '/login', to: 'user_sessions#new', as: :login
      post '/login', to: 'user_sessions#create', as: :create_new_session
      match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
      get '/signup', to: 'user_registrations#new', as: :signup
      post '/signup', to: 'user_registrations#create', as: :registration
      get '/password/recover', to: 'user_passwords#new', as: :recover_password
      post '/password/recover', to: 'user_passwords#create', as: :reset_password
      get '/password/change', to: 'user_passwords#edit', as: :edit_password
      put '/password/change', to: 'user_passwords#update', as: :update_password
      get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
    end

    get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
    put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration

    resources :account, controller: 'users'

    match '/access' => 'users#access', as: 'user_access', via: [:get]
    match '/access_login' => 'users#access_login', as: 'user_access_login', via: [:put, :post]
  end

  ##
  # Admins
  match '/admin/products/:id/erase', to: 'admin/products#erase', as: 'admin_erase_product', via: [:delete]

  ##
  # Seller
  resources :store_payment_methods
  get '/accepted_payments', to: 'store_payment_methods#index', as: 'accepted_payments'

  ##
  # Buyer

  resources :variants

  # Trading
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'order_cancel'


  get '/cart_link_dropdown', to: 'orders#cart_link_dropdown', as: 'cart_link_dropdown'

end

Rails.application.routes.draw do
  default_url_options :host => (Rails.env.production? ? 'shoppn.com' : 'localhost')

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  #########################
  # Filtering bots
  get '/:a/:b.php', to: 'errors#not_found'
  get '/:a.php', to: 'errors#not_found'

  ####################################################
  # Admins

  resources :site_categories, path: 'admin/site_categories'

  ####################################################
  # Additions to Spree
  namespace :spree, path: '/' do
    resources :stores, only: [:show, :index]
  end

  ##
  # Users
  namespace :users do
    resources :resource_action, only: [:index, :create, :destroy]
  end

  # Buyers

  get '/sellers/:id', to: 'sellers#show', as: :seller

  # Payments
  match '/payment_notifications/log' => 'payment_notifications#log', via: [:get, :put, :post], as: 'log_payment_notification'
  resources :payment_notifications

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spree/category_taxon.rb
module Spree
  class CategoryTaxon < Taxon

    TOP_CATEGORIES_CACHE_KEY = 'Spree::CategoryTaxon.top_categories'

    after_save :clear_cache

    def self.root
      self.where(name: 'Categories', parent_id: nil).last
    end

    ##
    # Find deepest category according to given +full_path+.
    # @return <Spree::Taxon>
    def self.find_by_full_path(full_path)
      levels = full_path.is_a?(Array) ? full_path : full_path.split(' > ')
      taxon = nil
      current_node = root
      levels.each do |cat_name|
        t = current_node.children.where(name: cat_name).first
        if t.nil?
          break
        else
          taxon = t
          current_node = t
        end
      end
      taxon
    end

    def self.find_or_create_categories_taxon()
      taxon = root
      taxon ||= ::Spree::Taxon.find_or_create_by!(taxonomy_id: find_or_create_categories_taxonomy.id) do|t|
        t.position = 0
        t.name = 'Categories'
        t.permalink = 'categories'
        t.depth = 0
      end
      taxon
    end

    def self.find_or_create_categories_taxonomy()
      ::Spree::Taxonomy.find_or_create_by!(name: 'Categories') do|t|
        t.position = 1
      end
    end

    ##
    # Cached top categories.
    def self.top_categories
      Rails.cache.fetch(TOP_CATEGORIES_CACHE_KEY, expires_in: 12.hours) do
        root.children
      end
    end

    protected

    def clear_cache
      Rails.cache.delete(TOP_CATEGORIES_CACHE_KEY)
    end
  end
end

app/models/spree/gateway/pay_pal_gateway_decorator.rb
Spree::Gateway::PayPalGateway.class_eval do
  attr_accessor :payment_method_id
end

app/models/spree/image_decorator.rb
module Spree
  Image.class_eval do

  end
end

app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do
  belongs_to :product

  before_save :set_references

  private

  def set_references
    self.product_id = variant.product_id
  end
end

app/models/spree/option_type_decorator.rb
module Spree
  OptionType.class_eval do
    validate :check_name

    VALID_OPTION_NAME_REGEX = /^((max|maximum|minmum|min|average|avg|estimate|est|US|UK|original|market|man'?s?|men'?s?|woman'?s?|women'?s?|kids?|adults?|new|supported|product|item)\s+)?([a-z]{2,}\s+)?(types?|category|name|colou?rs?|sizes?|number|no|sku|brand|width|length|height|diameter|radius|thickness|area|waist|bust|collar|weight|depth|models?|material|fabric|quality|quantity|count|pieces?|style|group|range|age|gender|level|class|capacity|time|date|life|season|quantity|version|edition|mode|port|payment|pattern|price|cost|charge|fee|rate|frequency|response|speed|bandwidth|volume|shape|method|current|voltage|percentage|ratio|frequency|condition|code|sleeve|sensitivity|grade|rating|platform|protocol|operating\s+system|format|angle|interface|standard)$/i

    DEFAULT_CACHE_KEY = 'DEFAULT_OPTION_TYPES'
    DEFAULT_OPTION_NAMES = ['color', 'clothing color', 'size', 'clothing size', 'shoe size']
    CATEGORY_NAMES_TO_OPTION_TYPE_NAMES_MAP = {
      /shoes?\s*\z/i => ['color', 'clothing color', 'shoe size'],
      /clothing|clothes/i => ['color', 'clothing color', 'size', 'clothing size']
    }

    after_save :clear_cache

    def self.valid_option_name?(name = '')
      !name.to_sanitized_keyword_name.match(VALID_OPTION_NAME_REGEX).nil?
    end

    ##
    # Iterates over list of category names, and find matches and their paired option type names
    # @category_names <Array of String>
    def self.default_option_types(category_names = [])
      option_names = Set.new
      category_names.each do|category_name|
        CATEGORY_NAMES_TO_OPTION_TYPE_NAMES_MAP.each_pair do|k, v|
          option_names += v if k =~ category_name
        end
      end
      self.where(name: option_names.to_a )
    end

    protected

    def check_name
      unless self.class.valid_option_name?(name)
        self.errors.add(:name)
      end
    end

    def clear_cache
      Rails.cache.delete(DEFAULT_CACHE_KEY)
    end
  end
end

app/models/spree/option_value_decorator.rb
module Spree
  OptionValue.class_eval do

    attr_accessor :variant_ids

    scope :with_names, lambda {|option_type_names|
        joins(:option_type).where("#{Spree::OptionType.table_name}.name IN (?)", option_type_names ) }
    scope :single_names, -> { where("name NOT LIKE '%/%' AND name NOT LIKE '% %'") }
    scope :multi_word_names, -> { where("name LIKE '%/%' OR name LIKE '% %'") }

    def option_type_name
      option_type.name
    end
  end
end

app/models/spree/order_decorator.rb
::Spree::Order.class_eval do

  before_save :generate_transaction_code

  ###############################
  # Overrides

  def finalize!
    ::Jobs::OrderJob.perform_async(id)
    super
  end

  ###############################
  # New methods

  ##
  # If +which_payment+ not given, would be latest payment w/ checkout state.
  def forward_to_process_payment?(which_payment = nil)
    which_payment ||= payments.checkout.last
    return false if which_payment.nil?

    which_payment.payment_method.is_a?(Spree::PaymentMethod::PayPal)
  end

  ##
  # @return <Spree::PaymentMethod>
  def payment_method_to_forward
    payments.checkout.last.try(:payment_method)
  end

  ##
  # 7-characters, alphanumeral.
  def self.random_transaction_code(id = nil)
    ( ( (id || rand(1000)) % 5) * 243 + rand(5987123654) ).to_s(36).rjust(7,'0').upcase
  end

  private

  def allow_cancel?
    return false unless (state == 'payment' || state == 'confirm' || completed? ) && state != 'canceled'
    shipment_state.nil? || %w{ready backorder pending}.include?(shipment_state)
  end

  def generate_transaction_code
    self.transaction_code = self.class.random_transaction_code(id) if transaction_code.blank?
  end

end

app/models/spree/payment_method/apple_pay.rb
module Spree
  class PaymentMethod::ApplePay < PaymentMethod

  end
end

app/models/spree/payment_method/credit_card_decorator.rb
::Spree::PaymentMethod::CreditCard.class_eval do

  def gateway_class
    # TODO:
  end

  def account_reference_label
    I18n.t('spree.card_number')
  end
end

app/models/spree/payment_method/google_pay.rb
module Spree
  class PaymentMethod::GooglePay < PaymentMethod

  end
end

app/models/spree/payment_method/pay_pal.rb
module Spree
  class PaymentMethod::PayPal < PaymentMethod
    def payment_source_class
      Spree::Gateway::PayPalGateway
    end

    def supports?(source)
      true
    end

    def source_required?
      false
    end

    def forward_payment_url

    end

  end
end

app/models/spree/payment_method_decorator.rb
Spree::PaymentMethod.class_eval do
  def self.populate_with_common_payment_methods
    ::Spree::PaymentMethod::PayPal.find_or_create_by(name: 'PayPal') do|pm|
      pm.description ='Pay with PayPal'
      pm.active = true
      pm.position = 1
      pm.available_to_users = true
    end
    ::Spree::PaymentMethod::CreditCard.find_or_create_by(name: 'Credit Card, Visa/MasterCard') do|pm|
      pm.description = 'Pay with credit cards like Visa or MasterCard'
      pm.active = true
      pm.position = 2
      pm.available_to_users = true
    end
    ::Spree::PaymentMethod::ApplePay.find_or_create_by(name: 'Apple Pay') do|pm|
      pm.description = 'Pay with ApplePay'
      pm.active = true
      pm.position = 3
      pm.available_to_users = true
    end
    ::Spree::PaymentMethod::GooglePay.find_or_create_by(name: 'Google Pay') do|pm|
      pm.description = 'Pay with GooglePay'
      pm.active = true
      pm.position = 4
      pm.available_to_users = true
    end
  end

  ##
  # Depending on payment method type, the attribute name that payer can refer to during payments;
  # for example, credit card needs 'card number' while PayPal simply needs 'Account ID'.
  def account_reference_label
    I18n.t('spree.account_id')
  end

  def forward_payment_url
    nil
  end
end

app/models/spree/permission_sets/seller_user.rb
##
# class SellerUser < DefaultCustomer
module Spree
  module PermissionSets
    class SellerUser < DefaultCustomer
      def activate!
        super

        # from Spree::PermissionSets::ProductManagement
        ::Spree::ProductUserRelation::MANAGEABLE_CLASSES.each do|klass|
          can :manage, klass, user_id: user.id if klass.new.respond_to?(:user_id)
          can [:new, :create], klass
        end

        # These don't have ref to product
        can :manage, Spree::Price
        can :manage, Spree::Image

        # somehow the looped 'can :manage' calls don't work
        can :manage, Spree::Product, user_id: user.id
        can [:new, :create], Spree::Product
        can :manage, Spree::OptionValue
        can :manage, Spree::StockItem

        # Cannot's
        cannot :manage, Spree::StockLocation
        cannot :erase, Spree::Product

        # exceptions that don't have actual model class as reference
        cannot :admin, :reports
      end

    end
  end
end

app/models/spree/permitted_attributes_decorator.rb
Spree::PermittedAttributes.class_variable_set('@@user_attributes', [:username, :display_name, :login, :password, :password_confirmation] )
Spree::PermittedAttributes.class_variable_set('@@store_payment_method_attributes', [:payment_method_id, :account_parameters, :account_label] )

app/models/spree/price_decorator.rb
module Spree
  Price.class_eval do

    after_save :update_variant

    def update_variant
      variant.update_sorting_rank!
    end
  end
end

app/models/spree/shipping_category.rb
module Spree
  class ShippingCategory < Spree::Base
    def self.default
      self.last || self.create(name: 'Default')
    end
  end
end

app/models/spree/shipping_category_decorator.rb
module Spree
  ShippingCategory.class_eval do
    def self.default
      self.last || self.create(name: 'Default')
    end
  end
end

app/models/spree/store_decorator.rb
::Spree::Store.class_eval do
  belongs_to :user
end

app/models/spree/store_selector/by_parameters.rb
# Override of ByServerName set at default at Spree::Config.current_store_selector_class.
# This looks at params (which include :controller and :action).
module Spree
  module StoreSelector
    class ByParameters

      def initialize(request)
        @request = request
      end

      # Chooses the current store based on a request.
      # @return [Spree::Store]
      def store
        _store_id = store_id
        ::Spree::User.logger.debug "| ByParameters: store_id #{_store_id}"
        store = _store_id ? ::Spree::Store.where(id: _store_id).first : nil
        store || Spree::Store.new
      end

      private

      # Those actions that loads actions like /stores/:id
      LOAD_STORE_ACTIONS = %w|show edit update destroy|
      LOAD_STORE_CONTROLLERS = %w|spree/stores|

      def params
        @request.try(:params) || {}
      end

      def store_id
        _store_id = params[:store_id]
        unless _store_id
          if LOAD_STORE_CONTROLLERS.include?(params[:controller]) && LOAD_STORE_ACTIONS.include?(params[:action])
            _store_id = params[:id]
          end
        end
        _store_id
      end
    end
  end
end

app/views/spree/variants/_variant_gallery.html.haml
- content_for :footer_extra do
  :javascript
    $(function(){
      refreshImageAndThumbnails('#{variant.id}');
      $("input[name='variant_id']").change(activateVariant);
      $(".product-thumbnails a[href]").click(loadImageOfThumbnail);
    });

- if variant.images.present?
  - images = variant.gallery.images
- else
  - images = variant.product.master.images

.product-gallery
  #thumbnails.thumbnails
    .make-me-sticky
      = render partial: 'spree/products/thumbnails', locals: { product: variant.product }
  .gallery-wrapper
    - cnt = 0
    - images.each_with_index do|image, index|
      - if index < 3
        .gallery-image
          = render partial: 'spree/shared/image', locals: { image: image, size: :large }
      - else
        .gallery-image.hidden
          = render partial: 'spree/shared/image', locals: { image: image, size: :large }
        - cnt += 1
    - if cnt > 0
      = link_to(content_tag(:h5, "+ #{cnt} more photos"), '#', class: 'btn show-more')
.product-carousel.owl-carousel.gallery-wrapper
  - images = is_prod ? variant.product.gallery.images : images
  - images.each_with_index do|image, index|
    .gallery-item(dash-hash="Image #{index}")
      = render partial: 'spree/shared/image', locals: { image: image, size: :large }

app/views/spree/variants/_variants_wrapper.html.haml
.container-fluid
  .row
    .sidebar-item.hidden-sm.hidden-xs
      .make-me-sticky
        .col
          %div{"data-hook" => "homepage_sidebar_navigation"}
            - if "spree/variants" == params[:controller] && @taxon
              = render partial: 'spree/shared/filters'
            - else
              = render partial: 'spree/shared/taxonomies'
    .col
      - if params[:keywords]
        %div{"data-hook" => "search_results"}
          - if @variants.empty?
            %h6.search-results-title= t('spree.no_products_found')
          - else
            = render partial: 'spree/shared/variants', locals: { variants: @variants, taxon: @taxon }
      - else
        %div{"data-hook" => "homepage_products"}
          = render partial: 'spree/shared/variants', locals: { variants: @variants, taxon: @taxon }

app/views/spree/variants/index.html.haml
= render partial: 'spree/variants/variants_wrapper', locals: { variants: @variants }
%br/
%br/
.text-center.pt-1.mb-4
  - if @variants.respond_to?(:total_pages)
    = paginate @variants

app/views/spree/variants/show.html.haml
:ruby
  @variant ||= resource
  @product ||= @variant.product if @variant
  @product_properties = @product.product_properties
  show_debug = %w|development staging|.include?(Rails.env)

- content_for :footer_extra do
  = javascript_include_tag 'spree/frontend/product'

- if spree_current_user
  #manage_actions.container.alert.alert-secondary.text-right
    - if can?(:manage, resource)
      = link_to('Edit Product', edit_admin_product_path(id: resource.product_id), class:'btn btn-warning')
      = link_to('Edit Variant', edit_admin_product_variant_path(product_id: resource.product.slug, id: resource.id), class:'btn btn-warning') unless resource.is_master?
      = link_to(t('spree.admin.variants.edit.modify_variants'), admin_product_variants_path(product_id: resource.slug), class:'btn btn-warning') unless resource.is_master?
      %br/
    - elsif can?(:manage, ::Spree::Product)
      = link_to('List This Item', new_admin_product_path(product:{master_product_id: resource.product_id}), class:'btn btn-success' )
/ Main Content Wrapper Start
- cache [I18n.locale, current_pricing_options, @variant] do
  %div(data-hook="product_show")
  .container
    .container.mb-12
    #content.main-content-wrapper
      .page-content-inner.enable-full-width
        #wrapper.row(data-hook="product_left_part_wrap")
          %ul.breadcrumbs
            - @variant.product.categories.each do|category_list|
              - category_list.each_with_index do|category, category_index|
                %li
                  = link_to(category.name, seo_url(category))
          .padding-top-2x.mt-2.hidden-sm-up.product-info-basic
            .col-9.product-title
              .product-taxon
                %span= @product.taxons.last ? @product.taxons.last.name : ''
              .product-title
                %h6= @product.name
            .col-3.text-right.product-price
              %h2= @product.price
          .content-section.col-lg-7.col-md-7.col-sm-7
            / ############## GALLERY SECTIONS ############
            .product-main-image
              .product-image(data-hook="product_images")
                .product-gallery__large-image
                  %figure.product-gallery__image
                    = render partial: 'variant_gallery', locals: { variant: @variant, is_prod: false }
          / ############## END GALLERY SECTION ############
          .col-lg-5.col-md-5.col-sm-5
            .make-me-sticky
              / ############## SIDEBAR SECTIONS ############
              .product-summary.mt--40.mt-md--10.mt-sm--30
                .product-info-basic
                  .col-9.product-title
                    .product-taxon
                      %span= @product.taxons.last ? @product.taxons.last.name : ''
                    .product-title
                      %h6= @product.name
                  .col-3.text-right.product-price
                    %h2
                      = '$' + @product.price.to_s
                - if show_debug && @variant.product.user
                  %h4.hidden
                    %strong Seller:
                    #{@variant.product.user.username}
                -# %p.text-muted
                  -# = product_description(@variant) rescue t('spree.product_has_no_description')
                  -# %a.scroll-to{:href => "#details"} More info
                .row.margin-top-1x
              #cart-form(data-hook="cart_form")
                = render partial: 'spree/products/cart_form_extended'

  / ############## END SIDEBAR SECTION ############
  / ############## Anything after the sidebar --- description etc. ############
  %br/
  %br/
  #details.bg-secondary.padding-top-2x.padding-bottom-2x.mb-3.mt-40.container
    .row
      .col-md-6
        %h3.h4 Details
        %p.mb-4
          = product_description(@variant) rescue t('spree.product_has_no_description')
      .col-md-6
        %div(data-hook="product_properties")
          = render partial: 'spree/products/properties'
        %div(data-hook="promotions")
          = render partial: 'spree/products/promotions'